# -*- coding: utf-8 -*-
"""task_7_sales_summary.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-2M2n1RinU22q2aX2O1_d4CwfZwh_nIr
"""

import sqlite3
import pandas as pd
import matplotlib.pyplot as plt

# Connect to the database
conn = sqlite3.connect('sales_data.db')
cursor = conn.cursor()

# Create the sales table
cursor.execute(
    "CREATE TABLE IF NOT EXISTS sales (product TEXT, quantity INTEGER, price REAL)"
)

# Insert data into the table
data = [
    ("Laptop", 2, 999.99),
    ("Laptop", 1, 999.99),
    ("Phone", 3, 499.99),
    ("Phone", 2, 499.99),
    ("Tablet", 4, 299.99),
    ("Tablet", 1, 299.99),
    ("Headphones", 5, 89.99),
    ("Headphones", 3, 89.99),
    ("Mouse", 10, 19.99),
    ("Mouse", 6, 19.99)
]
cursor.executemany("INSERT INTO sales (product, quantity, price) VALUES (?, ?, ?)", data)

# Commit changes and close the connection
conn.commit()
conn.close()
print("sales_data.db created!")

import pandas as pd
conn = sqlite3.connect("sales_data.db")
print(pd.read_sql_query("SELECT * FROM sales", conn))
conn.close()



# Connect to database
conn = sqlite3.connect("sales_data.db")

# Query 1: By product
query1 = """
SELECT
    product,
    SUM(quantity) AS total_quantity,
    SUM(quantity * price) AS total_revenue
FROM sales
GROUP BY product
"""
df1 = pd.read_sql_query(query1, conn)
print("Sales Summary by Product:")
print(df1)

# Query 2: Overall totals
query2 = """
SELECT
    SUM(quantity) AS total_quantity,
    SUM(quantity * price) AS total_revenue
FROM sales
"""
df2 = pd.read_sql_query(query2, conn)
print("\nOverall Sales Summary:")
print(df2)

# Bar chart
df1.plot(kind='bar', x='product', y='total_revenue', title='Revenue by Product')
plt.ylabel('Revenue ($)')
plt.xlabel('Product')
plt.tight_layout()
plt.savefig('sales_chart.png')
plt.show()

# Close connection
conn.close()

# Download files
from google.colab import files
files.download('sales_chart.png')
files.download('sales_data.db')